### ISSUE TITLE
Why is the function async?

### ISSUE THREAD

**Issue by ethanr-2000** [Ovyerus/deeppyer#6]
Hi, this library was really useful for a little project I was working on, so thank you!

I did however have to modify it so that the main function wasn't async. This was to be able to run it inside a function that I could not make async.

This seemed to have no effect on functionality. Is there a reason that it's async?

Cheers!

**Comment by Ovyerus** [comment]
Hey sorry for the late response.

The library used to rely on calling Microsoft's image API for face detection and used aiohttp for doing so, but has since moved to using OpenCV instead. I guess I forgot to change the function from async to regular in the process.
